name: Java CI with Maven and Spring Boot Build Image Push to Quay.io

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build project using Maven (including Spring Boot build-image)
      - name: Build with Maven and Spring Boot Build Image
        run: mvn -B spring-boot:build-image --file pom.xml
